apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: podlogmonitors.monitoring.mydomain.com
spec:
  group: monitoring.mydomain.com
  names:
    kind: PodLogMonitor
    listKind: PodLogMonitorList
    plural: podlogmonitors
    singular: podlogmonitor
  scope: Cluster
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                namespace:
                  type: string
                logMessage:
                  type: string
            status:
              type: object
              properties:
                lastRestartedPodName:
                  type: string
                lastRestartTime:
                  type: string
