---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: podlogmonitor-svc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podlogmonitor-role
  creationTimestamp: null
rules:
- apiGroups:
  - monitoring.mydomain.com
  resources:
  - podlogmonitors
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - monitoring.mydomain.com
  resources:
  - podlogmonitors/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - monitoring.mydomain.com
  resources:
  - podlogmonitors/finalizers
  verbs:
  - update
- apiGroups: [""]
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups: [""]
  resources:
  - pods/log
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: podlogmonitor-system-default
subjects:
- kind: ServiceAccount
  name: podlogmonitor-svc
  namespace: default
roleRef:
  kind: ClusterRole
  name: podlogmonitor-role
  apiGroup: rbac.authorization.k8s.io
