//go:build !ignore_autogenerated

/*
Copyright 2025 Saikiran Bitra.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
        runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodLogMonitor) DeepCopyInto(out *PodLogMonitor) {
        *out = *in
        out.TypeMeta = in.TypeMeta
        in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
        out.Spec = in.Spec
        out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodLogMonitor.
func (in *PodLogMonitor) DeepCopy() *PodLogMonitor {
        if in == nil {
                return nil
        }
        out := new(PodLogMonitor)
        in.DeepCopyInto(out)
        return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodLogMonitor) DeepCopyObject() runtime.Object {
        if c := in.DeepCopy(); c != nil {
                return c
        }
        return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodLogMonitorList) DeepCopyInto(out *PodLogMonitorList) {
        *out = *in
        out.TypeMeta = in.TypeMeta
        in.ListMeta.DeepCopyInto(&out.ListMeta)
        if in.Items != nil {
                in, out := &in.Items, &out.Items
                *out = make([]PodLogMonitor, len(*in))
                for i := range *in {
                        (*in)[i].DeepCopyInto(&(*out)[i])
                }
        }
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodLogMonitorList.
func (in *PodLogMonitorList) DeepCopy() *PodLogMonitorList {
        if in == nil {
                return nil
        }
        out := new(PodLogMonitorList)
        in.DeepCopyInto(out)
        return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PodLogMonitorList) DeepCopyObject() runtime.Object {
        if c := in.DeepCopy(); c != nil {
                return c
        }
        return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodLogMonitorSpec) DeepCopyInto(out *PodLogMonitorSpec) {
        *out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodLogMonitorSpec.
func (in *PodLogMonitorSpec) DeepCopy() *PodLogMonitorSpec {
        if in == nil {
                return nil
        }
        out := new(PodLogMonitorSpec)
        in.DeepCopyInto(out)
        return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodLogMonitorStatus) DeepCopyInto(out *PodLogMonitorStatus) {
        *out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodLogMonitorStatus.
func (in *PodLogMonitorStatus) DeepCopy() *PodLogMonitorStatus {
        if in == nil {
                return nil
        }
        out := new(PodLogMonitorStatus)
        in.DeepCopyInto(out)
        return out
}
